import { Airport } from '../model/airport.type';

export const Airports: Airport[] = [
  { id: 'atl', city: 'Atlanta', code: 'ATL' },
  { id: 'aus', city: 'Austin', code: 'AUS' },
  { id: 'bos', city: 'Boston', code: 'BOS' },
  { id: 'clt', city: 'Charlotte', code: 'CLT' },
  { id: 'den', city: 'Denver', code: 'DEN' },
  { id: 'dfw', city: 'Dallas', code: 'DFW' },
  { id: 'dtw', city: 'Detroit', code: 'DTW' },
  { id: 'ewr', city: 'Newark', code: 'EWR' },
  { id: 'fll', city: 'Fort Lauderdale', code: 'FLL' },
  { id: 'iah', city: 'Houston', code: 'IAH' },
  { id: 'jfk', city: 'New York', code: 'JFK' },
  { id: 'las', city: 'Las Vegas', code: 'LAS' },
  { id: 'lax', city: 'Los Angeles', code: 'LAX' },
  { id: 'mco', city: 'Orlando', code: 'MCO' },
  { id: 'mia', city: 'Miami', code: 'MIA' },
  { id: 'msp', city: 'Minneapolis', code: 'MSP' },
  { id: 'ord', city: 'Chicago', code: 'ORD' },
  { id: 'phl', city: 'Philadelphia', code: 'PHL' },
  { id: 'phx', city: 'Phoenix', code: 'PHX' },
  { id: 'san', city: 'San Diego', code: 'SAN' },
  { id: 'sea', city: 'Seattle', code: 'SEA' },
  { id: 'sfo', city: 'San Francisco', code: 'SFO' },
  { id: 'slc', city: 'Salt Lake City', code: 'SLC' },
];
